[target.x86_64-pc-windows-gnu]
rustflags = [
    "-C", "target-feature=+crt-static",  # 静态链接 C 运行时
    "-C", "link-args=-static",           # 强制静态链接所有库
    "-C", "link-args=-static-libgcc",    # 静态链接 libgcc
    "-C", "link-args=-static-libstdc++", # 静态链接 libstdc++
    "-C", "prefer-dynamic=no",
    "-C", "link-args=-Wl,--whole-archive -lwinpthread -Wl,--no-whole-archive",
    "-C", "link-args=-nodefaultlibs",
    "-C", "link-args=-lgcc_eh",
]

[release]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "prefer-dynamic=no"
]

