pub mod module_importer;
pub mod arg_structure;
pub mod ast;
pub mod builtin;
pub mod byte_code_vm;
pub mod constants;
pub mod lexer;
pub mod object;
pub mod parser;
pub mod runner;
pub mod token;
pub mod utils;
pub mod obj_enum;
// pub mod lg_ir_gen;
