pub mod builtin;
pub mod arg_structure;
pub mod ast;
pub mod byte_code_vm;
pub mod char_string;
pub mod constants;
pub mod environment;
pub mod lexer;
pub mod map;
pub mod module_system;
pub mod object;
pub mod parser;
pub mod runner;
pub mod token;
pub mod utils;
// pub mod lg_ir_gen;
